platform :ios, "8.0" 

target "MDRead" do

	pod 'AFNetworking', '~> 3.0'
    pod 'FMDB'
    pod 'SDWebImage', '~>3.7'
    pod 'pop', '~> 1.0'
    pod 'JSONKit'
    pod 'MJRefresh'
    pod 'MBProgressHUD'
end
